# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-08 23:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20170609_0114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='user_status',
            new_name='client_status',
        ),
    ]
