# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-03 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20170604_0016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='author',
        ),
        migrations.AddField(
            model_name='news',
            name='services',
            field=models.ManyToManyField(to='store.Service'),
        ),
    ]
