# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-09 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20170609_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='example@mail.com', max_length=254, verbose_name='E-mail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='client_status',
            field=models.BooleanField(default=False, verbose_name='согласие клиента'),
        ),
        migrations.AlterField(
            model_name='record',
            name='employee_status',
            field=models.BooleanField(default=False, verbose_name='согласие мастера'),
        ),
    ]
