# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-04 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_employee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(default='images/None/no-img-employees.jpg', upload_to='images/employees'),
        ),
    ]
