# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-04 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20170604_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default='images/None/no-img-employees.jpg', upload_to='images/services'),
        ),
    ]
