# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-04 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='cost',
            field=models.IntegerField(),
        ),
    ]
