# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-04 09:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20170604_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='add_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
