# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-04 11:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_service_add_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='services',
        ),
    ]
