# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-04 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_news_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('visit_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.Employee')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.Service')),
            ],
        ),
    ]
