# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-04 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
